# Pandas and Numpy

In [1]:
import numpy as np
import pandas as pd

In [113]:
import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [23]:
# from numpy import arange

In [2]:
# create an array of even numbers from 1 to 10 (including)
np.array([2, 4, 6, 8, 10])

array([ 2,  4,  6,  8, 10])

In [9]:
even_range_10 = [*range(0, 11, 2)][1::]

In [11]:
arr1 = np.array(even_range_10)
arr1

array([ 2,  4,  6,  8, 10])

In [16]:
# create a matrix of ones in 3x4 shape
np.ones((3,4), 'str')

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [12]:
arr1.shape

(5,)

In [24]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [25]:
# 10 100 (including), 15
np.linspace(10, 101, 15)

array([ 10. ,  16.5,  23. ,  29.5,  36. ,  42.5,  49. ,  55.5,  62. ,
        68.5,  75. ,  81.5,  88. ,  94.5, 101. ])

In [35]:
rand_arr = np.random.randint(10, 100, (2,3,2))
rand_arr

array([[[63, 64],
        [94, 38],
        [95, 67]],

       [[74, 93],
        [63, 79],
        [67, 91]]], dtype=int32)

In [34]:
np.random.uniform(1, 6, 5)

array([2.86814605, 5.40479886, 2.58401197, 4.51109559, 2.16705946])

In [33]:
arr1

array([ 2,  4,  6,  8, 10])

In [45]:
rand_arr[0, 0, 1]

np.int32(64)

In [50]:
rand_arr[0, 0:2, 0:2]

array([[63, 64],
       [94, 38]], dtype=int32)

In [37]:
rand_arr.shape

(2, 3, 2)

In [41]:
A = np.array([
    [1,2],
    [3,4] ] )

In [44]:
A[0,1]

np.int64(2)

In [43]:
A.shape

(2, 2)

In [51]:
# keep only even elements
rand_arr

array([[[63, 64],
        [94, 38],
        [95, 67]],

       [[74, 93],
        [63, 79],
        [67, 91]]], dtype=int32)

In [ ]:
rand_arr 

In [54]:
np.array([1,2,3,4,5]) + 2

array([3, 4, 5, 6, 7])

In [55]:
np.array([1,2,3,4,5]) > 2

array([False, False,  True,  True,  True])

In [62]:
 B = np.array([1,2,3,4,5])

B[B % 2 == 0]

array([2, 4])

In [63]:
rand_arr[rand_arr % 2 == 0]

array([64, 94, 38, 74], dtype=int32)

In [67]:
ls_a = [1,2,3,4,5]
for i in ls_a: 
    print(2 * i)

2
4
6
8
10


In [71]:
a = \
2 + 4

a

6

False

In [79]:
"hello".find('e', 2)

-1

In [ ]:
# 2x3 matrix + 3 array

In [90]:
M = np.random.randint(1, 10, (2,3))
a = np.random.randint(1, 10, (3))
print("Matrix:", M)
print("array:", a)

Matrix: [[3 5 1]
 [1 9 5]]
array: [9 8 1]


In [91]:
M + a

array([[12, 13,  2],
       [10, 17,  6]], dtype=int32)

In [87]:
[ 
    [7, 6, 3],
    [7, 6, 3]
]

[[7, 6, 3], [7, 6, 3]]

In [93]:
np.array([1,2,3]) + np.array([4,4,4])

array([5, 6, 7])

In [97]:
# create a column (series) named 'digits' containing digits from 0-9
pd.Series(data=[*range(0,10,1)], name = 'digits')

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: digits, dtype: int64

In [104]:
# create a dict with keys 'name', 'age', 'salary'
# values 'Alice', 25, 1000
info_dict = {
    "name": ['Alice', 'Bob'],
    "age": [25, 24],
    "salary": [1000, 2000],
}
info_dict
# convert it to DataFrame
df = pd.DataFrame(info_dict)

In [109]:
df.iloc[1, 0]

'Bob'

In [112]:
df.loc[1, "salary"]

np.int64(2000)

In [106]:
df

,name,age,salary
0,Alice,25,1000
1,Bob,24,2000
